import 'package:flutter/material.dart';
import 'package:flutter_application_1/myconsts.dart';

class HomePage extends StatelessWidget {
  const HomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        body: SingleChildScrollView(
          child: Column(
            children: [
              mycontainer(
                Colors.green,
                "text 1",
                Colors.indigo,
                20,
                FontWeight.bold,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                200,
                240,
                5,
                3,
                Colors.grey,
                () {},
              ),
              mycontainer(
                Colors.amber,
                "text 2",
                Colors.indigo,
                30,
                FontWeight.w400,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                220,
                230,
                7,
                0,
                Colors.blue,
                () {},
              ),
              mycontainer(
                Colors.teal,
                "text 3",
                Colors.red,
                12,
                FontWeight.w600,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                230,
                400,
                10,
                2.5,
                Colors.blue,
                () {},
              ),
              mycontainer(
                Colors.orange,
                "text 4",
                Colors.pink,
                18,
                FontWeight.w300,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                250,
                300,
                20,
                1.5,
                Colors.grey,
                () {},
              ),
              mycontainer(
                Colors.red,
                "text 5",
                Colors.amber,
                22,
                FontWeight.w400,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                300,
                400,
                30,
                1,
                Colors.orange,
                () {},
              ),
              mycontainer(
                Colors.purple,
                "text 6",
                Colors.white,
                23,
                FontWeight.w800,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                170,
                200,
                20,
                1,
                Colors.black,
                () {},
              ),
              mycontainer(
                Colors.grey,
                "text 7",
                Colors.red,
                32,
                FontWeight.w300,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                400,
                500,
                30,
                0.5,
                Colors.lightGreen,
                () {},
              ),
              mycontainer(
                Colors.black,
                "text 8",
                Colors.green,
                33,
                FontWeight.w800,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                500,
                600,
                20,
                0.5,
                Colors.teal,
                () {},
              ),
              mycontainer(
                Colors.pink,
                "text 9",
                Colors.yellow,
                40,
                FontWeight.bold,
                "italic ",
                "https://images.unsplash.com/photo-1714925298620-8103982a0c51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxOHx8fGVufDB8fHx8fA%3D%3D",
                130,
                150,
                25,
                0,
                Colors.cyanAccent,
                () {},
              ),
            ],
          ),
        ),
      ),
    );
  }
}
